name: kineto
description: Local-first Kineto desktop UI shell.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: '>=3.47.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.2.0
  hooks: ^2.2.0
  native_toolchain_rust: ^1.0.6
  wabisabi:
    git:
      url: https://github.com/bayanasar/wabisabi.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
